version: '3.9'

services:
  app:
    image: kadiraydogan/nero:latest
    container_name: nero-app
    ports:
      - '9090:8080'
    environment:
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    networks:
      - local-network

  redis:
    image: redis/redis-stack-server:7.2.0-v6
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "ping" ]
    volumes:
      - redis_data:/data
    networks:
      - local-network

volumes:
  redis_data:

networks:
  local-network:
    driver: bridge